/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const computed: typeof import('vue').computed
  const ref: typeof import('vue')['ref']
  const useCounter: typeof import('@vueuse/core').useCounter
  const useToggle: (typeof import('@vueuse/core'))['useToggle']
  const useLocal: typeof import('./src/composables/useLocal').useLocal
  const useDeparted: typeof import('./src/composables/useDeparted').useDeparted
}
