/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAlert: typeof import('element-plus/es')['ElAlert']
    Gone: typeof import('./src/components/Gone.vue')['default']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
  }
}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalDirectives {
    vFocus: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
