import fs from "node:fs";
import path from "node:path";
import { createRequire } from "node:module";
import { pathToFileURL } from "node:url";
import ts from "typescript";
import {
  findWorkspaceRoot,
  isPackageAvailable,
  readProjectManifest,
  workspaceLevels,
} from "../project/index.js";
import { isFile, toPosix } from "../shared/index.js";

// M82: styling generated live in the browser, so no static stylesheet was
// ever going to exist. Checked only once the fallback layer's ranked walk has
// no survivor — never before layers 1-3, and never as a reason to skip a real
// find.
// M114 A1 (fluentui-F3): the list is what the recogniser can name, not what
// exists. Griffel styles every Fluent v9 component and was absent, so a
// package whose only styling is `makeStyles` read as "no stylesheet found".
export const RUNTIME_STYLE_ENGINES = [
  "@ant-design/cssinjs",
  "antd-style",
  "@emotion/react",
  "@emotion/styled",
  "@emotion/css",
  "@griffel/react",
  "@griffel/core",
  "css-render",
  "styled-components",
  "primevue",
];

// M114 A2: the bindings a runtime styling engine exports. An import of one of
// them from a package the list does not name is an observation about the
// measured file, not a fact about the package's dependencies, and it is
// disclosed in weaker wording (report.ts, formatStylesheetsLine).
const RUNTIME_STYLE_BINDINGS = new Set(["makeStyles", "createUseStyles", "styled"]);

// The package a `makeStyles`/`createUseStyles`/`styled` binding was imported
// from in the measured file, when that package is not one the list above
// carries. Bare specifiers only: a relative import is the project's own code,
// not an engine.
export function unrecognisedRuntimeStyleEngine(measuredFile: string): string | undefined {
  let sourceText: string;
  try {
    sourceText = fs.readFileSync(measuredFile, "utf-8");
  } catch {
    return undefined;
  }
  const kind = /\.[jt]sx$/i.test(measuredFile) ? ts.ScriptKind.TSX : ts.ScriptKind.TS;
  const source = ts.createSourceFile(measuredFile, sourceText, ts.ScriptTarget.Latest, false, kind);
  for (const statement of source.statements) {
    if (!ts.isImportDeclaration(statement) || !statement.importClause) continue;
    if (!ts.isStringLiteral(statement.moduleSpecifier)) continue;
    const specifier = statement.moduleSpecifier.text;
    if (specifier.startsWith(".") || specifier.startsWith("/")) continue;
    if (RUNTIME_STYLE_ENGINES.includes(specifier)) continue;
    const clause = statement.importClause;
    const named = clause.namedBindings;
    const imported: string[] = [];
    if (clause.name) imported.push(clause.name.text);
    if (named && ts.isNamedImports(named)) {
      for (const element of named.elements) imported.push((element.propertyName ?? element.name).text);
    }
    if (imported.some((name) => RUNTIME_STYLE_BINDINGS.has(name))) return specifier;
  }
  return undefined;
}

export function detectRuntimeStyleEngines(
  projectRoot: string,
  workspaceRoot: string = findWorkspaceRoot(projectRoot),
): string[] {
  return RUNTIME_STYLE_ENGINES.filter((pkg) => isPackageAvailable(pkg, projectRoot, workspaceRoot));
}

// Vite's root is projectRoot, so an in-root stylesheet uses the same
// root-absolute form as the component import. Anything else needs /@fs/.
export function cssImportSpecifier(cssFile: string, projectRoot: string): string {
  const relative = path.relative(projectRoot, cssFile);
  if (relative.startsWith("..") || path.isAbsolute(relative)) {
    return "/@fs/" + toPosix(cssFile);
  }
  return "/" + toPosix(relative);
}

export function cssImportBlock(specifiers?: string[]): string {
  if (!specifiers || specifiers.length === 0) return "";
  return specifiers.map((s) => `import "${s}";`).join("\n") + "\n";
}

export function detectTailwindVite(projectRoot: string): boolean {
  return isPackageAvailable("@tailwindcss/vite", projectRoot);
}

// Loaded from the project's own node_modules: the harness never carries a
// Tailwind version of its own. Import failure is non-fatal: PostCSS may still
// be configured, and a missing plugin must not abort a measurement run.
export async function loadTailwindVitePlugin(projectRoot: string): Promise<unknown[]> {
  try {
    const require = createRequire(path.join(projectRoot, "/"));
    const entry = require.resolve("@tailwindcss/vite");
    const mod = await import(pathToFileURL(entry).href);
    const factory = mod.default ?? mod;
    if (typeof factory !== "function") {
      throw new Error("@tailwindcss/vite has no callable default export");
    }
    const plugin = factory();
    return Array.isArray(plugin) ? plugin : [plugin];
  } catch (err) {
    process.stderr.write(
      `Warning: could not load @tailwindcss/vite from ${projectRoot}: ${err instanceof Error ? err.message : String(err)}\n`,
    );
    return [];
  }
}

// M71: styling generated by a build step the harness does not run. Recognized
// so an unstyled-looking number is explainable; no plugin is ever loaded.
export const UNSUPPORTED_STYLE_ENGINES = [
  "unocss",
  "@unocss/vite",
  "@linaria/vite",
  "@linaria/core",
  "@pandacss/dev",
];

// M83 #6 (twenty-F5): package/resolution-chain availability alone used to be
// sufficient — a workspace member could declare @linaria/core and get the
// warning on every component in it, including one whose own import graph
// never touches it. `importedPackages` is the same `externalDeps` list the
// harness already builds from the measured component's (and wrapper's)
// resolved imports; membership there, not manifest/resolution-chain
// availability, is what earns this warning now.
export function detectUnsupportedStyleEngines(
  _projectRoot: string,
  _workspaceRoot: string,
  importedPackages: readonly string[],
): string[] {
  return UNSUPPORTED_STYLE_ENGINES.filter((pkg) => importedPackages.includes(pkg));
}

export function UNSUPPORTED_STYLE_ENGINE_WARNING(packages: string[]): string {
  return (
    `${packages.join(", ")} generates styles through a build step this harness does not run, so that ` +
    "styling is not replicated and the component may measure unstyled"
  );
}

// postcss-load-config's own search places, minus package.json.
const POSTCSS_CONFIG_FILES = [
  "postcss.config.ts",
  "postcss.config.cts",
  "postcss.config.mts",
  "postcss.config.js",
  "postcss.config.cjs",
  "postcss.config.mjs",
  ".postcssrc",
  ".postcssrc.json",
  ".postcssrc.yaml",
  ".postcssrc.yml",
  ".postcssrc.ts",
  ".postcssrc.cts",
  ".postcssrc.mts",
  ".postcssrc.js",
  ".postcssrc.cjs",
  ".postcssrc.mjs",
];

// Verified against the installed Vite 6.4.2: resolvePostcssConfig searches from
// its root up to searchForWorkspaceRoot(root) inclusive, and that helper knows
// only pnpm-workspace.yaml, lerna.json, and a package.json "workspaces" field.
// A repo whose root carries a lockfile alone stops Vite's walk at the member,
// so an inherited config is found here and passed in by hand. A member with its
// own config needs nothing: Vite's first level is already that directory.
export function findPostcssConfigAbove(
  memberRoot: string,
  workspaceRoot: string = findWorkspaceRoot(memberRoot),
): string | undefined {
  const hasConfig = (dir: string): boolean =>
    POSTCSS_CONFIG_FILES.some((name) => isFile(path.join(dir, name)));
  if (hasConfig(memberRoot)) return undefined;
  for (const level of workspaceLevels(memberRoot, workspaceRoot).slice(1)) {
    if (hasConfig(level)) return level;
  }
  return undefined;
}

// M111 A1 (midday-F1): Tailwind 3 has no Vite plugin of its own; it enters
// through PostCSS, and `resolveDefaultConfigPath` resolves `tailwind.config.*`
// against `process.cwd()`. A run started at the repository root of a monorepo
// therefore built a workspace member with Tailwind's *default* config -- empty
// `content`, no theme extension -- and `@apply` threw inside PostCSS. The
// config the member is built with has to come from the member, not the shell.
export const TAILWIND_CONFIG_FILES = [
  "tailwind.config.js",
  "tailwind.config.cjs",
  "tailwind.config.mjs",
  "tailwind.config.ts",
];

// Member first, then each ancestor up to and including the workspace root:
// Vite's own PostCSS search order, so the file found here is the file the
// pipeline would have used had it been started in the member.
function findPostcssConfigFile(memberRoot: string, workspaceRoot: string): string | undefined {
  for (const level of workspaceLevels(memberRoot, workspaceRoot)) {
    for (const name of POSTCSS_CONFIG_FILES) {
      const candidate = path.join(level, name);
      if (isFile(candidate)) return candidate;
    }
  }
  return undefined;
}

// `@tailwindcss/postcss` and `@tailwindcss/vite` are the version-4 entries; the
// bare `tailwindcss` plugin name is the version-3 one.
function postcssTextDeclaresBareTailwind(text: string): boolean {
  return /(?<![@\w/-])tailwindcss(?![\w/-])/.test(text);
}

// Installed metadata first, the declared range second: a fixture or a member
// measured before its install still states which major it means.
function tailwindMajor(memberRoot: string, workspaceRoot: string): number | undefined {
  const versions: string[] = [];
  // Bounded by the workspace: an install above the workspace root belongs to
  // whatever checkout this project happens to sit inside, not to this project.
  for (const level of workspaceLevels(memberRoot, workspaceRoot)) {
    const manifest = readProjectManifest(path.join(level, "node_modules", "tailwindcss"));
    if (typeof manifest?.version === "string") {
      versions.push(manifest.version);
      break;
    }
  }
  for (const level of workspaceLevels(memberRoot, workspaceRoot)) {
    const manifest = readProjectManifest(level);
    for (const field of ["dependencies", "devDependencies", "peerDependencies"] as const) {
      const deps = manifest?.[field] as Record<string, unknown> | undefined;
      const range = deps?.tailwindcss;
      if (typeof range === "string") versions.push(range);
    }
  }
  for (const version of versions) {
    const major = /(\d+)/.exec(version);
    if (major) return Number(major[1]);
  }
  return undefined;
}

export interface Tailwind3Pipeline {
  postcssConfigFile: string;
  configPath?: string;
  searched: string[];
}

// Undefined when nothing about this member is a Tailwind 3 PostCSS pipeline:
// no PostCSS config, a config that names no bare `tailwindcss` entry, or a
// major other than 3. The start directory is not an input -- that is the whole
// point of the milestone -- so it appears only in the message A3 builds.
export function resolveTailwind3Config(
  memberRoot: string,
  workspaceRoot: string = findWorkspaceRoot(memberRoot),
): Tailwind3Pipeline | undefined {
  if (detectTailwindVite(memberRoot)) return undefined;
  const postcssConfigFile = findPostcssConfigFile(memberRoot, workspaceRoot);
  if (postcssConfigFile === undefined) return undefined;
  let text: string;
  try {
    text = fs.readFileSync(postcssConfigFile, "utf-8");
  } catch {
    return undefined;
  }
  if (!postcssTextDeclaresBareTailwind(text)) return undefined;
  const major = tailwindMajor(memberRoot, workspaceRoot);
  if (major !== undefined && major !== 3) return undefined;
  const searched = workspaceLevels(memberRoot, workspaceRoot);
  for (const level of searched) {
    for (const name of TAILWIND_CONFIG_FILES) {
      const candidate = path.join(level, name);
      if (isFile(candidate)) return { postcssConfigFile, configPath: candidate, searched };
    }
  }
  return { postcssConfigFile, searched };
}

// M111 A3. Names what was looked for, where, and the directory this run was
// started in, because that directory is what Tailwind falls back to once the
// search comes back empty. It never names a build script: no script produces a
// config the repository does not carry.
export function TAILWIND3_CONFIG_MISSING_WARNING(searched: string[], startDir: string): string {
  return (
    `This project builds its CSS with Tailwind 3 through PostCSS, but none of ` +
    `${TAILWIND_CONFIG_FILES.join(", ")} was found in ${searched.join(", ")}. ` +
    `Tailwind then resolves its config from the directory the run started in ` +
    `(${startDir}) and falls back to its default config, whose content list is empty: ` +
    `utility classes and @apply rules resolve to nothing. Add one of those files to ${searched[0]}.`
  );
}

interface PostcssPluginDeclaration {
  name?: string;
  options?: unknown;
  instance?: unknown;
}

// The member's own config file decides the plugin list. Loaded, not parsed:
// the object map and the array forms both reach the same declarations, and a
// plugin the member instantiated itself passes through untouched.
async function readPostcssPluginDeclarations(
  file: string,
): Promise<PostcssPluginDeclaration[] | undefined> {
  if (![".js", ".cjs", ".mjs"].includes(path.extname(file))) return undefined;
  let config: unknown;
  try {
    config = createRequire(file)(file);
  } catch {
    const mod = (await import(pathToFileURL(file).href)) as { default?: unknown };
    config = mod.default ?? mod;
  }
  const plugins = (config as { plugins?: unknown } | undefined)?.plugins;
  if (Array.isArray(plugins)) {
    return plugins.map((entry) => {
      if (typeof entry === "string") return { name: entry };
      if (Array.isArray(entry) && typeof entry[0] === "string") {
        return { name: entry[0], options: entry[1] };
      }
      return { instance: entry };
    });
  }
  if (plugins && typeof plugins === "object") {
    return Object.entries(plugins as Record<string, unknown>)
      // PostCSS's object form disables a plugin with `false`. A disabled entry
      // is not part of the pipeline the member declared, so it produces none.
      .filter(([, options]) => options !== false)
      .map(([name, options]) => ({
      name,
      ...(options === true || options === null || options === undefined ? {} : { options }),
    }));
  }
  return undefined;
}

// M111 A1: the member's pipeline rebuilt with one difference -- its Tailwind 3
// entry receives the config path resolved from the member. Every other plugin
// the member declared keeps its own options and its own place in the order.
// Any failure returns undefined, which leaves the run on the directory-search
// behaviour it had before: a stylesheet decision is never worth aborting for.
// M111 A2 (midday-F1): Tailwind 3 resolves a relative `content` glob against
// `process.cwd()`, so the same config generated different CSS from different
// shell directories. This writes the member's config back out with every
// relative glob anchored to the member root and returns the generated file's
// path. A path, not an object: Tailwind's context cache is keyed by the config
// file path, and an object config rebuilds that context on every build.
export function writeAnchoredTailwind3Config(
  memberRoot: string,
  tailwindConfigPath: string,
  outputDir: string,
): string {
  const loadConfigPath = createRequire(path.join(memberRoot, "/")).resolve(
    "tailwindcss/loadConfig",
  );
  const generated = path.join(outputDir, "tailwind.anchored.config.cjs");
  const source = [
    `// Generated by 120fps: the member's own Tailwind config, with every relative`,
    "// `content` glob resolved against the member root instead of the directory",
    "// this run started in.",
    `const path = require("node:path");`,
    `const loaded = require(${JSON.stringify(loadConfigPath)});`,
    "const loadConfig = loaded.default || loaded;",
    `const base = ${JSON.stringify(memberRoot)};`,
    `const config = loadConfig(${JSON.stringify(tailwindConfigPath)});`,
    "const anchor = (glob) => {",
    `  if (typeof glob !== "string") return glob;`,
    `  const negated = glob.startsWith("!");`,
    "  const body = negated ? glob.slice(1) : glob;",
    "  if (path.isAbsolute(body)) return glob;",
    `  return (negated ? "!" : "") + path.resolve(base, body).split(path.sep).join("/");`,
    "};",
    "const content = config.content;",
    "module.exports = Array.isArray(content)",
    "  ? { ...config, content: content.map(anchor) }",
    `  : content && typeof content === "object"`,
    "    ? { ...config, content: { ...content, files: (content.files || []).map(anchor) } }",
    "    : config;",
    "",
  ].join("\n");
  fs.writeFileSync(generated, source);
  return generated;
}

export async function loadTailwind3PostcssPipeline(
  memberRoot: string,
  postcssConfigFile: string,
  tailwindConfigPath: string,
  outputDir?: string,
  onWarning?: (warning: string) => void,
): Promise<{ plugins: unknown[] } | undefined> {
  try {
    const declared = await readPostcssPluginDeclarations(postcssConfigFile);
    // A plugin list this reader cannot read -- a `.ts` postcss config, or a
    // `plugins` value that is neither an array nor an object -- leaves the run
    // on the directory-dependent search. Disclosed, never silent.
    if (declared === undefined) {
      onWarning?.(
        `Could not read a plugin list from ${postcssConfigFile}: Tailwind resolves its own config ` +
          `from the directory this run started in, so the result depends on that directory.`,
      );
      return undefined;
    }
    let configPath = tailwindConfigPath;
    if (outputDir !== undefined) {
      try {
        configPath = writeAnchoredTailwind3Config(memberRoot, tailwindConfigPath, outputDir);
      } catch (err) {
        onWarning?.(
          `Could not anchor the content globs of ${tailwindConfigPath} to ${memberRoot} ` +
            `(${err instanceof Error ? err.message : String(err)}): a relative glob in that config ` +
            `resolves against the directory this run started in, so the CSS built depends on it.`,
        );
      }
    }
    const require = createRequire(path.join(memberRoot, "/"));
    const plugins: unknown[] = [];
    for (const entry of declared) {
      if (entry.name === undefined) {
        plugins.push(entry.instance);
        continue;
      }
      // A member that already pinned a config path had no directory dependence
      // to take away, so its own value stands.
      const declaredConfig = (entry.options as Record<string, unknown> | undefined)?.config;
      const options =
        entry.name === "tailwindcss" && declaredConfig === undefined
          ? {
              ...(entry.options as Record<string, unknown> | undefined),
              config: configPath,
            }
          : entry.options;
      const loaded = (await import(pathToFileURL(require.resolve(entry.name)).href)) as {
        default?: unknown;
      };
      const factory = loaded.default ?? loaded;
      plugins.push(
        typeof factory === "function"
          ? (factory as (o?: unknown) => unknown)(options)
          : factory,
      );
    }
    return { plugins };
  } catch (err) {
    onWarning?.(
      `Could not rebuild the PostCSS pipeline from ${postcssConfigFile} with an explicit Tailwind ` +
        `config (${err instanceof Error ? err.message : String(err)}): Tailwind resolves its own ` +
        `config from the directory this run started in, so the result depends on that directory.`,
    );
    return undefined;
  }
}

export interface StyleTooling {
  tailwind: boolean;
  unsupportedEngines: string[];
  postcssConfigDir?: string;
  tailwind3ConfigPath?: string;
  tailwind3PostcssConfigFile?: string;
  warnings: string[];
}

// M71: the Tailwind plugin generates utility CSS for the classes the measured
// component uses. Whether a global stylesheet was also found says nothing about
// whether it is needed, so no stylesheet list reaches this decision.
export function resolveStyleTooling(
  projectRoot: string,
  workspaceRoot: string = findWorkspaceRoot(projectRoot),
  importedPackages: readonly string[] = [],
  startDir: string = process.cwd(),
): StyleTooling {
  const unsupportedEngines = detectUnsupportedStyleEngines(projectRoot, workspaceRoot, importedPackages);
  const postcssConfigDir = findPostcssConfigAbove(projectRoot, workspaceRoot);
  const tailwind3 = resolveTailwind3Config(projectRoot, workspaceRoot);
  const warnings =
    unsupportedEngines.length > 0 ? [UNSUPPORTED_STYLE_ENGINE_WARNING(unsupportedEngines)] : [];
  if (tailwind3 && tailwind3.configPath === undefined) {
    warnings.push(TAILWIND3_CONFIG_MISSING_WARNING(tailwind3.searched, startDir));
  }
  return {
    tailwind: detectTailwindVite(projectRoot),
    unsupportedEngines,
    warnings,
    ...(postcssConfigDir ? { postcssConfigDir } : {}),
    ...(tailwind3?.configPath
      ? {
          tailwind3ConfigPath: tailwind3.configPath,
          tailwind3PostcssConfigFile: tailwind3.postcssConfigFile,
        }
      : {}),
  };
}
