export { extractProps, extractExports, extractAllProps, detectScalingProps, type PropSchema, type ScalingPropMatch } from "./prop-gen.js";
export {
  inferComposition,
  type ExportInfo,
  type CompositionTree,
  type CompositionNode,
  type CompositionTemplate,
} from "./composition.js";
export {
  generateCombinations,
  generateDeltaPairs,
  generateScalingCombos,
  type PropCombination,
  type DeltaPair,
} from "./prop-gen-values.js";
export {
  buildAndServe,
  compositionToJsx,
  detectNextJs,
  buildShimAliases,
  detectWrapper,
  detectGlobalCss,
  detectTailwindVite,
  loadTailwindVitePlugin,
  detectReactCompiler,
  resolveReactCompiler,
  resolveReactCompilerState,
  loadReactCompilerPlugin,
  reactCompilerResolutionWarning,
  REACT_COMPILER_PACKAGE,
  REACT_COMPILER_DISABLED_WARNING,
  cssImportSpecifier,
  cssImportBlock,
  generateEntry,
  generateComposedEntry,
  scanExternalDeps,
  GLOBAL_CSS_CANDIDATES,
  SHIM_MODULES,
  WRAPPER_CANDIDATES,
  type HarnessResult,
  type BuildHarnessOptions,
  type ComponentIdentity,
  type EntryOptions,
  reactJsxRuntimeDeps,
  type ShimEntry,
  type ReactCompilerResolution,
  type ReactCompilerState,
} from "./harness.js";
export {
  measureMount,
  measureRerender,
  measureWrapperOverhead,
  applyWrapperViewport,
  settleStyles,
  needsStyleSettle,
  FONT_SETTLE_TIMEOUT_MS,
  FONT_SETTLE_WARNING,
  collectTrace,
  computeMedian,
  computeP95,
  parseTraceDuration,
  tryCollectGarbage,
  detectAnimations,
  enterHarness,
  runHarnessSession,
  mountAndWait,
  mountAndTrace,
  rerenderAndTrace,
  HARNESS_NAV_WAIT,
  type TraceEvent,
  type MeasureOptions,
  type MeasureRerenderOptions,
  type MountResult,
  type RerenderResult,
  type TimingResult,
  type HarnessSessionOptions,
} from "./measure.js";
export {
  discoverInteractions,
  type InteractionDescriptor,
  type InteractionType,
  type DiscoverOptions,
} from "./discovery.js";
export {
  explore,
  fnv1aHash,
  createRng,
  type StateNode,
  type StateEdge,
  type StateGraph,
  type PathStep,
  type ExploreOptions,
  type ExploreResult,
} from "./explorer.js";
export {
  parseMetrics,
  computeINP,
  computeScalingCurve,
  linearRegression,
  createCalibrationTrace,
  attributeCost,
  type CdpMetrics,
  type LongTask,
  type FrameTiming,
  type ScalingCurve,
  type ParseMetricsOptions,
  type CostAttribution,
  type CostBucket,
} from "./metrics.js";
export {
  computeCV,
  buildTimingWithCV,
  computeVerdict,
  classifyTier,
  formatTable,
  attachWrapperReport,
  DEFAULT_THRESHOLDS,
  TIER_BUDGETS,
  type ComponentTier,
  type TierBudget,
  type TimingWithCV,
  type ComboReport,
  type InteractionReport,
  type Report,
  type PropDelta,
  type Thresholds,
  type MachineInfo,
  type CalibrationResult,
  type BaselineComparison,
  type Regression,
  type Improvement,
  type NormalizedDelta,
  type EnvFingerprint,
  type EnvMatch,
  type WrapperReport,
  type CssReport,
  type ReactCompilerReport,
} from "./report.js";
export { analyze, buildReport, isFixturePath, detectFixture, hasScaleExport, resolveWrapPath, resolveCssFiles, type AnalyzeOptions, type BuildReportInput } from "./analyze.js";
export { detectScaleExport, loadTsconfigAliases, findProjectRoot, sweepStaleHarnessDirs, detectComponentExport } from "./harness.js";
export { scanExports } from "./prop-gen.js";
export { attachPageErrorCapture, enrichTimeoutError, type PageErrorCapture } from "./page-errors.js";
export {
  resolveStressPattern,
  executeStressPattern,
  findAriaGroupSiblings,
  type StressStep,
  type StressPattern,
} from "./stress-patterns.js";
export {
  detectFramework,
  diffSnapshots,
  detectMemoBailouts,
  detectContextFanOut,
  computeRenderAttribution,
  computePortalOrphans,
  hasReactWarning,
  injectProfilerHook,
  collectProfilerData,
  resetProfilerData,
  countBodyOrphans,
  generateProbeEntry,
  generateProbeHtml,
  runReactAnalysis,
  PROFILER_HOOK_SCRIPT,
  type ReactOptimizations,
  type ProfilerSnapshot,
  type ProfilerDiff,
  type FiberInfo,
  type RenderAttribution,
  type CallbackIdentityDelta,
  type ProbeEntryOptions,
  type ReactAnalysisOptions,
} from "./react-profiler.js";
export { parseArgs, resolveReactCompilerFlag, type CliArgs } from "./cli.js";
export {
  parseIsolationPhases,
  computeChurnDegradation,
  buildMemoryReport,
  buildStrictModeReport,
  buildRerenderIsolation,
  selectIsolationCombos,
  runIsolationPhases,
  computeIsolationVerdict,
  isolationBaselineMetrics,
  measureChurn,
  measureMemory,
  measureStrictMode,
  CHURN_CYCLES,
  CHURN_DEGRADATION_LIMIT,
  DEFAULT_MEMORY_CYCLES,
  ISOLATION_WARMUP_RUNS,
  MEMORY_WARMUP_CYCLES,
  LEAK_BYTES_PER_CYCLE,
  DEGENERATE_COMBO_WARNING,
  MEMORY_SKIPPED_WARNING,
  type IsolationPhase,
  type RerenderIsolation,
  type MemoryReport,
  type StrictModeReport,
  type IsolationReport,
  type IsolationComboSelection,
  type IsolationRunOptions,
  type IsolationRunResult,
  type MemoryMeasurement,
  type PhaseOptions,
} from "./isolation.js";
export {
  loadBudgetConfig,
  loadBaseline,
  saveBaseline,
  resolveComponentBudget,
  resolveTolerances,
  compareBaseline,
  buildEnvFingerprint,
  classifyEnv,
  describeEnvDiff,
  envAdvisory,
  UNKNOWN_ENV_WARNING,
  NORMALIZED_FLOOR_MS,
  type BudgetConfig,
  type ComponentBudget,
  type Baseline,
  type BaselineEntry,
  type BaselineEnvPolicy,
  type BaselineMetrics,
  type EnvFingerprintInput,
  type ResolvedTolerance,
} from "./budget.js";
