import { describe, it, expect, afterAll } from "vitest";
import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import { loadTsconfigAliases, TSCONFIG_EXTENDS_BROKEN_WARNING } from "../../src/harness.js";
import { explainProps } from "../../src/analyze.js";

const cleanupDirs: string[] = [];

afterAll(() => {
  for (const dir of cleanupDirs) fs.rmSync(dir, { recursive: true, force: true });
});

function mkProject(files: Record<string, string>): string {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "120fps-tsconf-extends-"));
  cleanupDirs.push(dir);
  for (const [rel, content] of Object.entries(files)) {
    const full = path.join(dir, rel);
    fs.mkdirSync(path.dirname(full), { recursive: true });
    fs.writeFileSync(full, content);
  }
  return dir;
}

const fwd = (p: string) => p.replace(/\\/g, "/");

// M95 (nuxt-ui-F1/F2): tsconfig.json extends ./.nuxt/tsconfig.json, which is
// generated by `nuxi prepare` and absent pre-build. TypeScript's own
// parseJsonConfigFileContent already reports this as a diagnostic (previously
// discarded); the empty prop schema that results downstream is a direct
// consequence a user could not otherwise connect to this cause.
describe("loadTsconfigAliases: broken tsconfig extends chain (M95)", () => {
  it("warns naming the config file and the missing extends target", () => {
    const dir = mkProject({
      "tsconfig.json": JSON.stringify({ extends: "./.nuxt/tsconfig.json" }),
      "src/x.ts": "export const x = 1;",
    });
    const warnings: string[] = [];
    const aliases = loadTsconfigAliases(dir, warnings);
    expect(aliases).toEqual([]);
    expect(warnings.some((w) => w.includes(fwd(dir)) && w.includes(".nuxt/tsconfig.json"))).toBe(
      true,
    );
  });

  it("still resolves paths declared directly in the config, alongside the broken-extends warning", () => {
    const dir = mkProject({
      "tsconfig.json": JSON.stringify({
        extends: "./.nuxt/tsconfig.json",
        compilerOptions: { paths: { "@/*": ["./src/*"] } },
      }),
      "src/x.ts": "export const x = 1;",
    });
    const warnings: string[] = [];
    const aliases = loadTsconfigAliases(dir, warnings);
    expect(aliases).toHaveLength(1);
    expect(aliases[0].find.test("@/thing")).toBe(true);
    expect(warnings.some((w) => w.includes(".nuxt/tsconfig.json"))).toBe(true);
  });

  it("produces no warning and no change for a config whose extends chain fully resolves", () => {
    const dir = mkProject({
      "tsconfig.json": JSON.stringify({ extends: "./base.json" }),
      "base.json": JSON.stringify({ compilerOptions: { paths: { "@/*": ["./src/*"] } } }),
      "src/x.ts": "export const x = 1;",
    });
    const warnings: string[] = [];
    const aliases = loadTsconfigAliases(dir, warnings);
    expect(aliases).toHaveLength(1);
    expect(warnings).toEqual([]);
  });

  it("attributes a broken workspace-root extends chain to the root config file, independent of the member layer", () => {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), "120fps-tsconf-extends-ws-"));
    cleanupDirs.push(root);
    fs.writeFileSync(path.join(root, "pnpm-workspace.yaml"), "packages:\n  - member\n");
    fs.writeFileSync(
      path.join(root, "tsconfig.json"),
      JSON.stringify({ extends: "./.generated/tsconfig.json" }),
    );
    const member = path.join(root, "member");
    fs.mkdirSync(member, { recursive: true });
    fs.writeFileSync(path.join(member, "tsconfig.json"), JSON.stringify({ compilerOptions: {} }));

    const warnings: string[] = [];
    loadTsconfigAliases(member, warnings);
    expect(
      warnings.some((w) => w.includes(fwd(root)) && w.includes(".generated/tsconfig.json")),
    ).toBe(true);
  });

  it("names both halves in TSCONFIG_EXTENDS_BROKEN_WARNING directly", () => {
    const text = TSCONFIG_EXTENDS_BROKEN_WARNING("/repo/tsconfig.json", "File '/repo/.nuxt/tsconfig.json' not found.");
    expect(text).toContain("/repo/tsconfig.json");
    expect(text).toContain(".nuxt/tsconfig.json");
  });
});

// M92/M95 (nuxt-ui-F2): --explain-props never called loadTsconfigAliases at
// all, so a dry run reported "0 props" on every nuxt-ui candidate with no
// cause named, while a full run's own harness build (src/harness.ts:2464)
// already surfaced TSCONFIG_EXTENDS_BROKEN_WARNING for the identical broken
// chain. Lane A's M95 fix only reached the full-run path; this closes the
// dry-run gap.
describe("explainProps names a broken tsconfig extends chain (M92, nuxt-ui-F2)", () => {
  it("includes TSCONFIG_EXTENDS_BROKEN_WARNING when the component reports 0 props under a broken extends chain", async () => {
    const dir = mkProject({
      "package.json": JSON.stringify({ name: "broken-extends-app" }),
      "tsconfig.json": JSON.stringify({ extends: "./.nuxt/tsconfig.json" }),
      // assertReactDomClient needs a resolvable react-dom/client; a plain
      // file under node_modules satisfies createRequire(...).resolve without
      // a real react-dom install.
      "node_modules/react-dom/client.js": "module.exports = {};",
      // Untyped: genuinely 0 props, independent of the broken chain -- this
      // isolates "the warning is present" from Lane B's own type-resolution
      // behavior, which this milestone does not own.
      "src/Untyped.jsx": "export default function Untyped(props) { return null; }",
    });
    const explained = await explainProps(path.join(dir, "src/Untyped.jsx"));
    expect(explained.props).toEqual([]);
    const broken = explained.warnings.filter(
      (w) => w.includes(fwd(dir)) && w.includes(".nuxt/tsconfig.json"),
    );
    expect(broken).toHaveLength(1);
  });

  // M100 (I5): `collectStaticPreBuildWarnings` runs `loadTsconfigAliases` as
  // its own first step, so the direct call `explainProps` used to make
  // alongside it would have reported the identical broken chain twice.
  it("names the broken chain once, not once per probe that reads the tsconfig", async () => {
    const dir = mkProject({
      "package.json": JSON.stringify({ name: "broken-extends-once" }),
      "tsconfig.json": JSON.stringify({ extends: "./.nuxt/tsconfig.json" }),
      "node_modules/react-dom/client.js": "module.exports = {};",
      "src/Untyped.jsx": "export default function Untyped(props) { return null; }",
    });
    const explained = await explainProps(path.join(dir, "src/Untyped.jsx"));
    const seen = new Map<string, number>();
    for (const w of explained.warnings) seen.set(w, (seen.get(w) ?? 0) + 1);
    expect([...seen.entries()].filter(([, n]) => n > 1)).toEqual([]);
  });

  it("does not fire when the extends chain fully resolves", async () => {
    const dir = mkProject({
      "package.json": JSON.stringify({ name: "healthy-extends-app" }),
      "tsconfig.json": JSON.stringify({ extends: "./base.json" }),
      "base.json": JSON.stringify({ compilerOptions: {} }),
      "node_modules/react-dom/client.js": "module.exports = {};",
      "src/Untyped.jsx": "export default function Untyped(props) { return null; }",
    });
    const explained = await explainProps(path.join(dir, "src/Untyped.jsx"));
    expect(explained.props).toEqual([]);
    expect(explained.warnings.some((w) => w.includes("tsconfig.json"))).toBe(false);
  });
});
